# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d4a45c5dbf8309e69cb34251cc31251144b70513c3329cd3772e6f85795ca568b1e6fb89558cc32fb9ef7bc11190b14e2eb3a16ae9d8b4757d2de44734ee260

test:
  secret_key_base: f23d53faf92aa0aff60210bda9f43b0348e6b421b9ecb74c56bea5df0f93e6d20795ea0f52619d87be76da3fda57e0fb80ee4b58484fe5be7d2b608943f1417e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
